# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-GB

# Site title
title: "X. Eileen Pan"

# A description of your site for meta tag, search engine results.
description: "Hi there! I am Eileen and I am a PhD student in pure mathematics with a focus in algebra, in particular group theory.
"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: #

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: href="/about/"
  - text: Archive
    url: /style-guide/
  - text: Tags
    url: /tags/
#  - text: Download
#    url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
#disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; All rights reserved. "
  has_social: true

  ## => Markdown Enhancements
##############################

## Mathjax
mathjax: true
mathjax_autoNumber: true

## Mermaid
mermaid: false

## Chart
chart: # false (default), true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
